# AUTO-GENERATED. Do not edit manually.\n# Generated by AdultIncomePred.ipynb\n\nimport math\nimport pandas as pd\n\n
FEATURE_NAMES = ['age', 'workclass', 'fnlwgt', 'education.num', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'capital.gain', 'capital.loss', 'hours.per.week']
NUMERIC_COLUMNS = ['age', 'fnlwgt', 'education.num', 'capital.gain', 'capital.loss', 'hours.per.week']
CATEGORICAL_COLUMNS = ['workclass', 'marital.status', 'occupation', 'relationship', 'race', 'sex']
NUMERIC_MEDIANS = {'age': 37.0, 'fnlwgt': 178356.0, 'education.num': 10.0, 'capital.gain': 0.0, 'capital.loss': 0.0, 'hours.per.week': 40.0}
CATEGORY_MAPPINGS = {'workclass': {'?': 0, 'Federal-gov': 1, 'Local-gov': 2, 'Never-worked': 3, 'Private': 4, 'Self-emp-inc': 5, 'Self-emp-not-inc': 6, 'State-gov': 7, 'Without-pay': 8}, 'marital.status': {'Married': 0, 'NotMarried': 1, 'Separated': 2, 'Widowed': 3}, 'occupation': {'?': 0, 'Adm-clerical': 1, 'Armed-Forces': 2, 'Craft-repair': 3, 'Exec-managerial': 4, 'Farming-fishing': 5, 'Handlers-cleaners': 6, 'Machine-op-inspct': 7, 'Other-service': 8, 'Priv-house-serv': 9, 'Prof-specialty': 10, 'Protective-serv': 11, 'Sales': 12, 'Tech-support': 13, 'Transport-moving': 14}, 'relationship': {'Husband': 0, 'Not-in-family': 1, 'Other-relative': 2, 'Own-child': 3, 'Unmarried': 4, 'Wife': 5}, 'race': {'Amer-Indian-Eskimo': 0, 'Asian-Pac-Islander': 1, 'Black': 2, 'Other': 3, 'White': 4}, 'sex': {'Female': 0, 'Male': 1}}
SCALER_MEANS = [38.59052518427519, 3.8717751842751844, 189618.77361025798, 10.0908707002457, 0.7687730343980343, 6.593212530712531, 1.443911240786241, 3.66492628992629, 0.6671913390663391, 1050.3629453316953, 89.22719594594595, 40.48579545454545]
SCALER_SCALES = [13.599983714466859, 1.453382496676158, 105569.58584337578, 2.5602679427046846, 0.8351609766765171, 4.234777623724564, 1.6056427668770241, 0.8504920859000504, 0.4712186924785608, 7220.233742712061, 407.28373456696374, 12.37512989830532]
INVERSE_TARGET_MAPPING = {'0': '<=50K', '1': '>50K'}


def _load_input(data):
    if isinstance(data, str):
        return pd.read_csv(data), False

    if isinstance(data, pd.DataFrame):
        return data.copy(), False

    return data, True


def _preprocess(data):
    df, is_vector = _load_input(data)

    if is_vector:
        row = [float(x) for x in data]

        if len(row) != len(FEATURE_NAMES):
            raise ValueError(
                f"Expected {len(FEATURE_NAMES)} encoded features, "
                f"received {len(row)}."
            )

        rows = [row]

    else:
        missing = [
            c for c in FEATURE_NAMES
            if c not in df.columns
        ]

        if missing:
            raise ValueError(
                "Input CSV is missing required columns: "
                + str(missing)
            )

        df = df[FEATURE_NAMES].copy()

        # Numeric preprocessing
        for col in NUMERIC_COLUMNS:
            df[col] = pd.to_numeric(
                df[col],
                errors="coerce"
            )

            df[col] = df[col].fillna(
                NUMERIC_MEDIANS[col]
            )

        # Categorical preprocessing
        for col in CATEGORICAL_COLUMNS:
            series = (
                df[col]
                .astype("string")
                .fillna("__MISSING__")
                .str.strip()
            )

            df[col] = (
                series
                .map(CATEGORY_MAPPINGS[col])
                .fillna(-1)
                .astype(float)
            )

        rows = df.astype(float).values.tolist()

    # Standard scaling
    return [
        [
            (float(v) - mean) / scale
            for v, mean, scale
            in zip(
                row,
                SCALER_MEANS,
                SCALER_SCALES
            )
        ]
        for row in rows
    ]


def predict(data):
    scaled_rows = _preprocess(data)

    predictions = [
        _predict_one(row)
        for row in scaled_rows
    ]

    return (
        predictions[0]
        if len(predictions) == 1
        else predictions
    )


def predict_labels(data):
    predictions = predict(data)

    if not isinstance(predictions, list):
        predictions = [predictions]

    return [
        INVERSE_TARGET_MAPPING[str(int(p))]
        for p in predictions
    ]

def score(input):
    if input[4] <= -0.32182182371616364:
        if input[3] <= 0.9409676194190979:
            if input[9] <= 0.5602501630783081:
                if input[3] <= -0.6213688254356384:
                    if input[10] <= 4.179574728012085:
                        if input[11] <= 0.2435695379972458:
                            if input[2] <= 0.09507687389850616:
                                if input[11] <= -1.0493461787700653:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.8902439024390244, 0.10975609756097561]
                            else:
                                if input[3] <= -1.0119529366493225:
                                    var0 = [0.9693877551020408, 0.030612244897959183]
                                else:
                                    var0 = [0.8709677419354839, 0.12903225806451613]
                        else:
                            if input[0] <= 0.4345207214355469:
                                if input[2] <= 1.2960572838783264:
                                    var0 = [0.9210526315789473, 0.07894736842105263]
                                else:
                                    var0 = [0.8181818181818182, 0.18181818181818182]
                            else:
                                if input[0] <= 1.0962861776351929:
                                    var0 = [0.75, 0.25]
                                else:
                                    var0 = [0.8860759493670886, 0.11392405063291139]
                    else:
                        if input[10] <= 4.665722370147705:
                            if input[5] <= 1.5128982067108154:
                                var0 = [0.0, 1.0]
                            else:
                                var0 = [0.5, 0.5]
                        else:
                            var0 = [1.0, 0.0]
                else:
                    if input[0] <= -0.2272447794675827:
                        if input[10] <= 4.185713052749634:
                            if input[0] <= -0.7419512867927551:
                                if input[3] <= -0.23078471049666405:
                                    var0 = [0.9202733485193622, 0.07972665148063782]
                                else:
                                    var0 = [0.8189415041782729, 0.181058495821727]
                            else:
                                if input[3] <= -0.23078471049666405:
                                    var0 = [0.7908745247148289, 0.20912547528517111]
                                else:
                                    var0 = [0.6870860927152318, 0.3129139072847682]
                        else:
                            if input[10] <= 4.665722370147705:
                                if input[0] <= -0.8154807686805725:
                                    var0 = [0.3333333333333333, 0.6666666666666666]
                                else:
                                    var0 = [0.02857142857142857, 0.9714285714285714]
                            else:
                                if input[2] <= 0.5588136613368988:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.75, 0.25]
                    else:
                        if input[10] <= 4.157477140426636:
                            if input[11] <= -0.4836955666542053:
                                if input[6] <= 1.591941088438034:
                                    var0 = [0.8861111111111111, 0.11388888888888889]
                                else:
                                    var0 = [0.6826923076923077, 0.3173076923076923]
                            else:
                                if input[3] <= -0.23078471049666405:
                                    var0 = [0.6518199233716475, 0.3481800766283525]
                                else:
                                    var0 = [0.5191846522781774, 0.48081534772182255]
                        else:
                            if input[10] <= 4.665722370147705:
                                if input[0] <= 1.3168747425079346:
                                    var0 = [0.0078125, 0.9921875]
                                else:
                                    var0 = [0.1111111111111111, 0.8888888888888888]
                            else:
                                if input[10] <= 5.088032245635986:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.5357142857142857, 0.4642857142857143]
            else:
                if input[0] <= 2.27275812625885:
                    if input[3] <= -2.1837052702903748:
                        if input[2] <= -0.3488862216472626:
                            var0 = [0.0, 1.0]
                        else:
                            var0 = [0.5, 0.5]
                    else:
                        if input[0] <= 1.6109927296638489:
                            var0 = [0.0, 1.0]
                        else:
                            if input[8] <= -0.3548062741756439:
                                var0 = [0.2857142857142857, 0.7142857142857143]
                            else:
                                if input[5] <= -0.73043093085289:
                                    var0 = [0.16666666666666666, 0.8333333333333334]
                                else:
                                    var0 = [0.0, 1.0]
                else:
                    if input[9] <= 1.9747473001480103:
                        var0 = [0.8, 0.2]
                    else:
                        var0 = [0.0, 1.0]
        else:
            if input[9] <= 0.5602501630783081:
                if input[10] <= 4.157477140426636:
                    if input[11] <= -0.7665208876132965:
                        if input[6] <= 1.591941088438034:
                            if input[3] <= 1.722135841846466:
                                if input[0] <= -0.44783326983451843:
                                    var0 = [0.9655172413793104, 0.034482758620689655]
                                else:
                                    var0 = [0.7054263565891473, 0.29457364341085274]
                            else:
                                if input[11] <= -1.3725751638412476:
                                    var0 = [0.5909090909090909, 0.4090909090909091]
                                else:
                                    var0 = [0.23529411764705882, 0.7647058823529411]
                        else:
                            if input[2] <= 0.8666627407073975:
                                if input[2] <= 0.15583301335573196:
                                    var0 = [0.4473684210526316, 0.5526315789473685]
                                else:
                                    var0 = [0.0, 1.0]
                            else:
                                if input[0] <= 0.10363797657191753:
                                    var0 = [0.75, 0.25]
                                else:
                                    var0 = [0.75, 0.25]
                    else:
                        if input[0] <= -0.9625397622585297:
                            if input[11] <= 0.32437676191329956:
                                if input[2] <= -0.42962443828582764:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.8076923076923077, 0.19230769230769232]
                            else:
                                if input[0] <= -1.0360692739486694:
                                    var0 = [0.8571428571428571, 0.14285714285714285]
                                else:
                                    var0 = [0.5, 0.5]
                        else:
                            if input[9] <= 0.2866440564393997:
                                if input[10] <= 1.3252991810441017:
                                    var0 = [0.314540059347181, 0.685459940652819]
                                else:
                                    var0 = [0.8695652173913043, 0.13043478260869565]
                            else:
                                if input[9] <= 0.4704331159591675:
                                    var0 = [0.6923076923076923, 0.3076923076923077]
                                else:
                                    var0 = [1.0, 0.0]
                else:
                    if input[10] <= 4.665722370147705:
                        if input[0] <= -0.7419512867927551:
                            if input[2] <= 0.09421961940824986:
                                var0 = [0.0, 1.0]
                            else:
                                var0 = [0.25, 0.75]
                        else:
                            if input[1] <= -1.6319001913070679:
                                if input[0] <= 0.3977559953927994:
                                    var0 = [0.0, 1.0]
                                else:
                                    var0 = [0.25, 0.75]
                            else:
                                var0 = [0.0, 1.0]
                    else:
                        if input[10] <= 5.10521936416626:
                            var0 = [1.0, 0.0]
                        else:
                            if input[1] <= -0.5998250395059586:
                                var0 = [0.2, 0.8]
                            else:
                                var0 = [0.0, 1.0]
            else:
                if input[0] <= 1.7580517530441284:
                    var0 = [0.0, 1.0]
                else:
                    if input[0] <= 1.8315812349319458:
                        var0 = [0.25, 0.75]
                    else:
                        if input[11] <= -1.4533823132514954:
                            var0 = [0.16666666666666666, 0.8333333333333334]
                        else:
                            var0 = [0.0, 1.0]
    else:
        if input[9] <= 0.8433434963226318:
            if input[3] <= 0.9409676194190979:
                if input[10] <= 5.2279839515686035:
                    if input[11] <= 0.32437676191329956:
                        if input[0] <= -0.7419512867927551:
                            if input[2] <= -1.5703270435333252:
                                if input[2] <= -1.5756457448005676:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.5, 0.5]
                            else:
                                if input[5] <= 0.686408519744873:
                                    var0 = [0.9996958637469586, 0.00030413625304136254]
                                else:
                                    var0 = [0.997134670487106, 0.0028653295128939827]
                        else:
                            if input[5] <= 0.686408519744873:
                                if input[5] <= -0.4942910075187683:
                                    var0 = [0.9740840035746202, 0.025915996425379804]
                                else:
                                    var0 = [0.9944478716841456, 0.005552128315854411]
                            else:
                                if input[5] <= 1.1586883664131165:
                                    var0 = [0.9174041297935103, 0.08259587020648967]
                                else:
                                    var0 = [0.9685264663805436, 0.031473533619456366]
                    else:
                        if input[0] <= -0.00665627233684063:
                            if input[1] <= 1.1203002631664276:
                                if input[6] <= 0.034932270646095276:
                                    var0 = [0.9548494983277592, 0.0451505016722408]
                                else:
                                    var0 = [0.9907407407407407, 0.009259259259259259]
                            else:
                                if input[7] <= -2.5454983711242676:
                                    var0 = [0.5714285714285714, 0.42857142857142855]
                                else:
                                    var0 = [0.9158878504672897, 0.08411214953271028]
                        else:
                            if input[9] <= 0.501110777258873:
                                if input[3] <= -0.23078471049666405:
                                    var0 = [0.9244712990936556, 0.0755287009063444]
                                else:
                                    var0 = [0.8206896551724138, 0.1793103448275862]
                            else:
                                if input[5] <= 0.21412870287895203:
                                    var0 = [0.75, 0.25]
                                else:
                                    var0 = [0.0, 1.0]
                else:
                    if input[2] <= -0.6078291833400726:
                        if input[2] <= -0.9934373795986176:
                            var0 = [0.5, 0.5]
                        else:
                            var0 = [0.0, 1.0]
                    else:
                        if input[11] <= 0.04155144654214382:
                            if input[0] <= 0.912462443113327:
                                if input[0] <= 0.030108477920293808:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.5714285714285714, 0.42857142857142855]
                            else:
                                var0 = [1.0, 0.0]
                        else:
                            if input[10] <= 5.652749300003052:
                                if input[11] <= 0.5667984485626221:
                                    var0 = [0.6, 0.4]
                                else:
                                    var0 = [1.0, 0.0]
                            else:
                                var0 = [0.14285714285714285, 0.8571428571428571]
            else:
                if input[11] <= 0.2435695379972458:
                    if input[0] <= -0.3007742762565613:
                        if input[10] <= 3.429483413696289:
                            if input[0] <= -0.6684217751026154:
                                if input[4] <= 0.8755521327257156:
                                    var0 = [0.9916897506925207, 0.008310249307479225]
                                else:
                                    var0 = [0.9285714285714286, 0.07142857142857142]
                            else:
                                if input[5] <= 0.5683385580778122:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.9044117647058824, 0.09558823529411764]
                        else:
                            if input[10] <= 3.6529147624969482:
                                var0 = [0.0, 1.0]
                            else:
                                if input[10] <= 4.976316690444946:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.5, 0.5]
                    else:
                        if input[10] <= 5.588911771774292:
                            if input[3] <= 1.722135841846466:
                                if input[11] <= -0.7665208876132965:
                                    var0 = [0.9666666666666667, 0.03333333333333333]
                                else:
                                    var0 = [0.8497023809523809, 0.15029761904761904]
                            else:
                                if input[8] <= -0.3548062741756439:
                                    var0 = [0.8285714285714286, 0.17142857142857143]
                                else:
                                    var0 = [0.4444444444444444, 0.5555555555555556]
                        else:
                            var0 = [0.0, 1.0]
                else:
                    if input[0] <= -0.7419512867927551:
                        if input[0] <= -0.8154807686805725:
                            if input[11] <= 1.7789070010185242:
                                if input[10] <= 3.9487773180007935:
                                    var0 = [0.9858156028368794, 0.014184397163120567]
                                else:
                                    var0 = [0.75, 0.25]
                            else:
                                if input[0] <= -0.9625397622585297:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.7272727272727273, 0.2727272727272727]
                        else:
                            if input[11] <= 0.4859912097454071:
                                var0 = [1.0, 0.0]
                            else:
                                if input[1] <= -0.5998250395059586:
                                    var0 = [1.0, 0.0]
                                else:
                                    var0 = [0.7037037037037037, 0.2962962962962963]
                    else:
                        if input[10] <= 5.553309917449951:
                            if input[8] <= -0.3548062741756439:
                                if input[3] <= 1.722135841846466:
                                    var0 = [0.7912087912087912, 0.2087912087912088]
                                else:
                                    var0 = [0.45454545454545453, 0.5454545454545454]
                            else:
                                if input[4] <= 0.8755521327257156:
                                    var0 = [0.6826923076923077, 0.3173076923076923]
                                else:
                                    var0 = [0.5177304964539007, 0.48226950354609927]
                        else:
                            var0 = [0.0, 1.0]
        else:
            if input[0] <= -1.2566577196121216:
                var0 = [0.75, 0.25]
            else:
                if input[9] <= 1.0035183727741241:
                    if input[3] <= 0.5503835119307041:
                        if input[0] <= 0.0668732263147831:
                            var0 = [1.0, 0.0]
                        else:
                            var0 = [0.5, 0.5]
                    else:
                        var0 = [0.0, 1.0]
                else:
                    var0 = [0.0, 1.0]
    return var0



def _predict_one(scaled_array):

    result = score(scaled_array)

    if isinstance(
        result,
        (list, tuple)
    ):
        return int(
            max(
                range(len(result)),
                key=lambda i: result[i]
            )
        )

    return (
        1
        if float(result) >= 0.5
        else 0
    )
