# AUTO-GENERATED. Do not edit manually.\n# Generated by AdultIncomePred.ipynb\n\nimport math\nimport pandas as pd\n\n
FEATURE_NAMES = ['age', 'workclass', 'fnlwgt', 'education.num', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'capital.gain', 'capital.loss', 'hours.per.week']
NUMERIC_COLUMNS = ['age', 'fnlwgt', 'education.num', 'capital.gain', 'capital.loss', 'hours.per.week']
CATEGORICAL_COLUMNS = ['workclass', 'marital.status', 'occupation', 'relationship', 'race', 'sex']
NUMERIC_MEDIANS = {'age': 37.0, 'fnlwgt': 178356.0, 'education.num': 10.0, 'capital.gain': 0.0, 'capital.loss': 0.0, 'hours.per.week': 40.0}
CATEGORY_MAPPINGS = {'workclass': {'?': 0, 'Federal-gov': 1, 'Local-gov': 2, 'Never-worked': 3, 'Private': 4, 'Self-emp-inc': 5, 'Self-emp-not-inc': 6, 'State-gov': 7, 'Without-pay': 8}, 'marital.status': {'Married': 0, 'NotMarried': 1, 'Separated': 2, 'Widowed': 3}, 'occupation': {'?': 0, 'Adm-clerical': 1, 'Armed-Forces': 2, 'Craft-repair': 3, 'Exec-managerial': 4, 'Farming-fishing': 5, 'Handlers-cleaners': 6, 'Machine-op-inspct': 7, 'Other-service': 8, 'Priv-house-serv': 9, 'Prof-specialty': 10, 'Protective-serv': 11, 'Sales': 12, 'Tech-support': 13, 'Transport-moving': 14}, 'relationship': {'Husband': 0, 'Not-in-family': 1, 'Other-relative': 2, 'Own-child': 3, 'Unmarried': 4, 'Wife': 5}, 'race': {'Amer-Indian-Eskimo': 0, 'Asian-Pac-Islander': 1, 'Black': 2, 'Other': 3, 'White': 4}, 'sex': {'Female': 0, 'Male': 1}}
SCALER_MEANS = [38.59052518427519, 3.8717751842751844, 189618.77361025798, 10.0908707002457, 0.7687730343980343, 6.593212530712531, 1.443911240786241, 3.66492628992629, 0.6671913390663391, 1050.3629453316953, 89.22719594594595, 40.48579545454545]
SCALER_SCALES = [13.599983714466859, 1.453382496676158, 105569.58584337578, 2.5602679427046846, 0.8351609766765171, 4.234777623724564, 1.6056427668770241, 0.8504920859000504, 0.4712186924785608, 7220.233742712061, 407.28373456696374, 12.37512989830532]
INVERSE_TARGET_MAPPING = {'0': '<=50K', '1': '>50K'}

import math 
import numpy as np
import pandas as pd

def _load_input(data):
    if isinstance(data, str):
        return pd.read_csv(data), False

    if isinstance(data, pd.DataFrame):
        return data.copy(), False

    return data, True


def _preprocess(data):
    df, is_vector = _load_input(data)

    if is_vector:
        row = [float(x) for x in data]

        if len(row) != len(FEATURE_NAMES):
            raise ValueError(
                f"Expected {len(FEATURE_NAMES)} encoded features, "
                f"received {len(row)}."
            )

        rows = [row]

    else:
        missing = [
            c for c in FEATURE_NAMES
            if c not in df.columns
        ]

        if missing:
            raise ValueError(
                "Input CSV is missing required columns: "
                + str(missing)
            )

        df = df[FEATURE_NAMES].copy()

        # Numeric preprocessing
        for col in NUMERIC_COLUMNS:
            df[col] = pd.to_numeric(
                df[col],
                errors="coerce"
            )

            df[col] = df[col].fillna(
                NUMERIC_MEDIANS[col]
            )

        # Categorical preprocessing
        for col in CATEGORICAL_COLUMNS:
            series = (
                df[col]
                .astype("string")
                .fillna("__MISSING__")
                .str.strip()
            )

            df[col] = (
                series
                .map(CATEGORY_MAPPINGS[col])
                .fillna(-1)
                .astype(float)
            )

        rows = df.astype(float).values.tolist()

    # Standard scaling
    return [
        [
            (float(v) - mean) / scale
            for v, mean, scale
            in zip(
                row,
                SCALER_MEANS,
                SCALER_SCALES
            )
        ]
        for row in rows
    ]


def predict(data):
    scaled_rows = _preprocess(data)

    predictions = [
        _predict_one(row)
        for row in scaled_rows
    ]

    return (
        predictions[0]
        if len(predictions) == 1
        else predictions
    )


def predict_labels(data):
    predictions = predict(data)

    if not isinstance(predictions, list):
        predictions = [predictions]

    return [
        INVERSE_TARGET_MAPPING[str(int(p))]
        for p in predictions
    ]

def _predict_one(scaled_array):

    classes = [0, 1]
    priors = [0.7591753685503686, 0.24082463144963145]
    means = [[-0.13067850674346318, -0.029134852317567003, 0.004947228919208802, -0.1898301649319551, 0.20335758685032504, -0.04021576434171073, 0.14224975262635983, -0.04108084335006417, -0.12381041430536138, -0.12430366330228225, -0.0853808963043546, -0.12771672034718407], [0.4119508163322127, 0.09184468429460181, -0.015595640343910935, 0.5984204545717894, -0.6410642882138246, 0.1267761421739786, -0.44842800226147467, 0.1295032165227624, 0.3902998474237756, 0.3918547651527617, 0.26915466673341476, 0.40261408335185617]]
    variances = [[1.0581837560488796, 1.0166749013185132, 1.0124833936665916, 0.8967307202061968, 0.9733581656142369, 1.0144273416626757, 0.9285015613184063, 1.073520248093465, 1.072528400907178, 0.017837611113076867, 0.5997134667654022, 0.996711870530081], [0.5930449872083737, 0.9363227317130807, 0.9603269851052987, 0.8538407021298021, 0.5426569924953233, 0.9333486745718947, 0.9605151773786558, 0.7461436505665208, 0.5707043765429589, 3.8939087649525512, 2.1664380383889688, 0.7968468503636029]]

    log_scores = []

    for i in range(len(classes)):

        score_value = math.log(
            max(priors[i], 1e-300)
        )

        for j, value in enumerate(scaled_array):

            variance = max(
                variances[i][j],
                1e-12
            )

            mean = means[i][j]

            score_value += (
                -0.5
                * math.log(
                    2.0
                    * math.pi
                    * variance
                )
            )

            score_value += (
                -((value - mean) ** 2)
                / (2.0 * variance)
            )

        log_scores.append(score_value)

    return int(
        classes[
            log_scores.index(
                max(log_scores)
            )
        ]
    )
