import math 
import numpy as np
import pandas as pd

# AUTO-GENERATED. Do not edit manually.\n# Generated by AdultIncomePred.ipynb\n\nimport math\nimport pandas as pd\n\n
FEATURE_NAMES = ['age', 'workclass', 'fnlwgt', 'education.num', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'capital.gain', 'capital.loss', 'hours.per.week']
NUMERIC_COLUMNS = ['age', 'fnlwgt', 'education.num', 'capital.gain', 'capital.loss', 'hours.per.week']
CATEGORICAL_COLUMNS = ['workclass', 'marital.status', 'occupation', 'relationship', 'race', 'sex']
NUMERIC_MEDIANS = {'age': 37.0, 'fnlwgt': 178356.0, 'education.num': 10.0, 'capital.gain': 0.0, 'capital.loss': 0.0, 'hours.per.week': 40.0}
CATEGORY_MAPPINGS = {'workclass': {'?': 0, 'Federal-gov': 1, 'Local-gov': 2, 'Never-worked': 3, 'Private': 4, 'Self-emp-inc': 5, 'Self-emp-not-inc': 6, 'State-gov': 7, 'Without-pay': 8}, 'marital.status': {'Married': 0, 'NotMarried': 1, 'Separated': 2, 'Widowed': 3}, 'occupation': {'?': 0, 'Adm-clerical': 1, 'Armed-Forces': 2, 'Craft-repair': 3, 'Exec-managerial': 4, 'Farming-fishing': 5, 'Handlers-cleaners': 6, 'Machine-op-inspct': 7, 'Other-service': 8, 'Priv-house-serv': 9, 'Prof-specialty': 10, 'Protective-serv': 11, 'Sales': 12, 'Tech-support': 13, 'Transport-moving': 14}, 'relationship': {'Husband': 0, 'Not-in-family': 1, 'Other-relative': 2, 'Own-child': 3, 'Unmarried': 4, 'Wife': 5}, 'race': {'Amer-Indian-Eskimo': 0, 'Asian-Pac-Islander': 1, 'Black': 2, 'Other': 3, 'White': 4}, 'sex': {'Female': 0, 'Male': 1}}
SCALER_MEANS = [38.59052518427519, 3.8717751842751844, 189618.77361025798, 10.0908707002457, 0.7687730343980343, 6.593212530712531, 1.443911240786241, 3.66492628992629, 0.6671913390663391, 1050.3629453316953, 89.22719594594595, 40.48579545454545]
SCALER_SCALES = [13.599983714466859, 1.453382496676158, 105569.58584337578, 2.5602679427046846, 0.8351609766765171, 4.234777623724564, 1.6056427668770241, 0.8504920859000504, 0.4712186924785608, 7220.233742712061, 407.28373456696374, 12.37512989830532]
INVERSE_TARGET_MAPPING = {'0': '<=50K', '1': '>50K'}

def _load_input(data):
    if isinstance(data, str):
        return pd.read_csv(data), False

    if isinstance(data, pd.DataFrame):
        return data.copy(), False

    return data, True


def _preprocess(data):
    df, is_vector = _load_input(data)

    if is_vector:
        row = [float(x) for x in data]

        if len(row) != len(FEATURE_NAMES):
            raise ValueError(
                f"Expected {len(FEATURE_NAMES)} encoded features, "
                f"received {len(row)}."
            )

        rows = [row]

    else:
        missing = [
            c for c in FEATURE_NAMES
            if c not in df.columns
        ]

        if missing:
            raise ValueError(
                "Input CSV is missing required columns: "
                + str(missing)
            )

        df = df[FEATURE_NAMES].copy()

        # Numeric preprocessing
        for col in NUMERIC_COLUMNS:
            df[col] = pd.to_numeric(
                df[col],
                errors="coerce"
            )

            df[col] = df[col].fillna(
                NUMERIC_MEDIANS[col]
            )

        # Categorical preprocessing
        for col in CATEGORICAL_COLUMNS:
            series = (
                df[col]
                .astype("string")
                .fillna("__MISSING__")
                .str.strip()
            )

            df[col] = (
                series
                .map(CATEGORY_MAPPINGS[col])
                .fillna(-1)
                .astype(float)
            )

        rows = df.astype(float).values.tolist()

    # Standard scaling
    return [
        [
            (float(v) - mean) / scale
            for v, mean, scale
            in zip(
                row,
                SCALER_MEANS,
                SCALER_SCALES
            )
        ]
        for row in rows
    ]


def predict(data):
    scaled_rows = _preprocess(data)

    predictions = [
        _predict_one(row)
        for row in scaled_rows
    ]

    return (
        predictions[0]
        if len(predictions) == 1
        else predictions
    )


def predict_labels(data):
    predictions = predict(data)

    if not isinstance(predictions, list):
        predictions = [predictions]

    return [
        INVERSE_TARGET_MAPPING[str(int(p))]
        for p in predictions
    ]

def score(input):
    return -1.7031179999672732 + input[0] * 0.5399750788547192 + input[1] * -0.03866108622893468 + input[2] * 0.06319606040948672 + input[3] * 0.8905715257066087 + input[4] * -1.1307052102477577 + input[5] * 0.03846140340310273 + input[6] * 0.14036366445188786 + input[7] * 0.10231806397149125 + input[8] * 0.20688711545008984 + input[9] * 2.2657364906417916 + input[10] * 0.278082223800094 + input[11] * 0.42389925789190824



def _predict_one(scaled_array):

    result = score(scaled_array)

    if isinstance(
        result,
        (list, tuple)
    ):
        return int(
            max(
                range(len(result)),
                key=lambda i: result[i]
            )
        )

    return (
        1
        if float(result) >= 0.5
        else 0
    )
